import scipy.stats as stats
import random

def single_year_simulation(dist_geburtenRate, dist_todesRaten, dist_einwanderung, dist_auswanderung, startValue, years):
    def generateDistribution_rvs(distr_type_params, pop_start, current_pop, sample_size=10000):
        """
        generate rvs from distribution

        params:
        distr_type_params: distribution parameters from fitter
        pop_start: start population size
        current_pop: current population size
        sample_size: number of values generated by rvs function
        """
        
        key = list(distr_type_params.keys())[0]
        params = distr_type_params[key].copy()

        params["loc"] = (params["loc"] / pop_start) * current_pop
        params["scale"] = (params["scale"] / pop_start) * current_pop

        obj = getattr(stats, key)

        try:
            dist_vals = obj.rvs(size=sample_size, **params)
        except:
            raise
    
        return dist_vals

    valuesYear = [startValue]

    for year in range(years):
        birthed =  random.choice(generateDistribution_rvs(dist_geburtenRate, startValue, valuesYear[-1]))
        dead = random.choice(generateDistribution_rvs(dist_todesRaten, startValue, valuesYear[-1]))
        eingewandert = random.choice(generateDistribution_rvs(dist_einwanderung, startValue, valuesYear[-1]))
        ausgewandert = random.choice(generateDistribution_rvs(dist_auswanderung, startValue, valuesYear[-1]))

        newValue = valuesYear[-1] + birthed - dead + eingewandert - ausgewandert
        valuesYear.append(newValue)

    return valuesYear